# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-03-25 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_404_middleware', '0002_ignorable404referer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(unique=True)),
                ('num_occurrences', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
